### ISSUE TITLE
Improve `DApp` script processes

### ISSUE THREAD

**Issue by relu91** [vaimee/desmo-dapp#4]
Currently, the DApp uses a set of `bat` files to handle the build process, the deployment, and tests. Bat files have two main issues:
- They are windows only
- Nodejs users are not used to using bat files during development. 

To solve this issue we should refactor the current logic inside the `scripts` folder to be performed as a set of `npm run` calls. Moreover, being a TS project the DApp needs to be conformant to a regular TS library or application workflow. This means reducing the usage of ts-node and configuring a build process. Running tests should be also compliant with the previously mentioned process. 

For a reference check: https://github.com/vaimee/desmo-sdk

**Comment by FerrariAndrea** [comment]
That PR includes PR #8 which resolves Issue #2.
The branch `issue#4_scripts` has already been merged with `issue#2_callbackhell`.
